name: CI-CD

on:
  push: 
    branches: ["main"]
  workflow_dispatch: 
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar no Docker Hub
        run: echi "Executando o comando Docker Login"
      - name: Construcao da Imagem Docker
        run: echi "Executando o comando Docker build"
      - name: Envio da Imagem Docker
        run: echi "Executando o comando Docker push"
        
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar na AWS
        run: echi "Executando o comando aws configure"
      - name: Configurar o kubectl
        run: echi "Executando o comando aws eks update-kubeconfig"
      - name: Deploy dos manifestos no Kubernetes
        run: echi "Executando o comando Kubectl apply"

    


