name: CI-CD

on:
  push: 
    branches: ["main"]
  workflow_dispatch: 
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter cofigo do projeto
        uses: actions/checkout@v4.2.2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construcao da Imagem Docker
        run: echo "Executando o comando Docker build"
      - name: Envio da Imagem Docker
        run: echo "Executando o comando Docker push"
        
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticar na AWS
        run: echo "Executando o comando aws configure"
      - name: Configurar o kubectl
        run: echo "Executing o comando aws eks update-kubeconfig"
      - name: Deploy dos manifestos no Kubernetes
        run: echo "Executando o comando Kubectl apply"

    


